imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme

    default_locale: %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        compass:
            sass: /var/lib/gems/1.8/gems/sass-3.1.15/bin/sass
            bin: /var/lib/gems/1.8/gems/compass-0.11.7/bin/compass
        sass:
            bin: /var/lib/gems/1.8/gems/sass-3.1.15/bin/sass
            compass: /var/lib/gems/1.8/gems/compass-0.11.7/bin/compass
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Doctrine MongoDB Configuration
doctrine_mongodb:
    default_database: admingen_db
    auto_generate_proxy_classes: %kernel.debug%
    auto_generate_hydrator_classes: %kernel.debug%
    connections:
        default:
            server:  mongodb://localhost:27017
            options:
                connect: true
    document_managers:
        default:
            metadata_cache_driver: apc
            mappings:
                AdmingeneratorDoctrineODMDemoBundle: ~
            auto_mapping: false

# Propel
propel:
    path:       "%kernel.root_dir%/../vendor/propel/propel1"
    phing_path: "%kernel.root_dir%/../vendor/phing"
    dbal:
        driver:               mysql
        user:                 %database_user%
        password:             %database_password%
        dsn:                  mysql:host=%database_host%;dbname=%database_name%;charset=UTF8
        options:              {}
        attributes:           {}

# Swiftmailer Configuration
#swiftmailer:
#    transport: %mailer_transport%
#    host:      %mailer_host%
#    username:  %mailer_user%
#    password:  %mailer_password%

security:
    acl: ~

jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false
    expressions: true
#jms_aop:
#   cache_dir: %kernel.cache_dir%/jms_aop

knp_menu:
    twig: true
admingenerator_generator:
    base_admin_template: AdmingeneratorActiveAdminThemeBundle::base_admin.html.twig
    knp_menu_class: Admingenerator\DemoBundle\Menu\AdminMenu
    use_doctrine_orm: true
    use_doctrine_odm: true
    use_propel: true

fos_user:
    service:
        mailer: fos_user.mailer.noop
    user_class:  FOS\UserBundle\Propel\UserProxy
    propel_user_class: FOS\UserBundle\Propel\User
    db_driver: propel
    firewall_name: main
