AdmingeneratorDoctrineODMDemoActorBundle_admin_admingenerator_doctrine_odm_demo_actor_bundle:
    resource: "@AdmingeneratorDoctrineODMDemoActorBundle/Controller/"
    type:     admingenerator
    prefix:   /admin-demo-odm-actor

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
_admindemo:
    resource: "@AdmingeneratorDemoBundle/Controller/"
    type:     admingenerator
    prefix:   /admin-demo

_admindemoodm:
    resource: "@AdmingeneratorDoctrineODMDemoBundle/Controller/"
    type:     admingenerator
    prefix:   /admin-demo-odm
