# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
_admindemo:
    resource: "@AdmingeneratorDemoBundle/Controller/"
    type:     admingenerator
    prefix:   /admin-demo
