_welcome:
    pattern:  /
    defaults: { _controller: AdmingeneratorDemoBundle:List:index }
    
AdmingeneratorDoctrineODMDemoActorBundle_admin_admingenerator_doctrine_odm_demo_actor_bundle:
    resource: "@AdmingeneratorDoctrineODMDemoBundle/Controller/Actor/"
    type:     admingenerator
    prefix:   /admin-demo-odm-actor

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
_admindemo:
    resource: "@AdmingeneratorDemoBundle/Controller/"
    type:     admingenerator
    prefix:   /admin-demo

_admindemoodm:
    resource: "@AdmingeneratorDoctrineODMDemoBundle/Controller/"
    type:     admingenerator
    prefix:   /admin-demo-odm

_admindemopropel:
    resource: "@AdmingeneratorPropelDemoBundle/Controller/"
    type:     admingenerator
    prefix:   /admin-demo-propel

## FOS User
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

