generator: admingenerator.generator.doctrine
params:
  model: Admingenerator\DemoBundle\Entity\Movie
  namespace_prefix: Admingenerator
  bundle_name: DemoBundle
  fields: 
    producer:
      label: Producer name
      sort_on: producer.name
      getter: producer.name
      addFormOptions:
        property: name
builders:
  list:
    params:
      title: Here is a beautifull title no  ???
      display: [ id, title, is_published, producer ]
      max_per_page: 3
      actions:
        new: ~ 
      object_actions:
        edit: ~ 
        delete: ~
  filters: 
    params:
      display: [ title, is_published, producer ]
  new: 
    params:
      title: You're creating a new movie
      display: [ title, is_published, producer]
      actions:
        list: ~
  edit: 
    params:
      title: You're editing the movie "{{ Movie.title }}"
      display: [ title, is_published, producer, actors ]
      actions:
        list: ~
  delete: ~ 
